eye = input('Please enter a character for the eye:')
print("##########")
print("#  ", eye, eye ," #")
print("#        #")
print("##########")
print("    ##    ")
print("    ##    ")
print("##  ##  ##")
print("#   ##   #")
print("#   ##   #")
print("    ##    ")
print(" #  ##  # ")
print(" #      # ")
print(" #      # ")
print(" #      # ")